# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mai-kun.Clippy
PackageVersion: 1.1.1
InstallerType: inno
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Mai-kun/Clippy/releases/download/v1.1.1/Clippy-Setup.exe
  InstallerSha256: 1422BE7B15874A3F13C34873FCEADB0AF7D727156C20D22AF8950FB462D8FBD6
ManifestType: installer
ManifestVersion: 1.12.0
