# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Mai-kun.Clippy
PackageVersion: 1.1.1
PackageLocale: en-US
Publisher: Mai-kun
PackageName: Clippy
License: MIT License
ShortDescription: Lightweight zero-copy instant replay screen recorder for Windows
ManifestType: defaultLocale
ManifestVersion: 1.12.0
